CREATE DATABASE IF NOT EXISTS `CATEGORYS` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `CATEGORYS`;

CREATE TABLE `CATEGORY` (
  `name` VARCHAR(42),
  `image` VARCHAR(42),
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRODUCT` (
  `name` VARCHAR(42),
  `description` VARCHAR(42),
  `image` VARCHAR(42),
  `status` VARCHAR(42),
  `price` VARCHAR(42),
  `name_1` VARCHAR(42),
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `PRODUCT` ADD FOREIGN KEY (`name_1`) REFERENCES `CATEGORY` (`name`);